from typing import List

from .schemas import ConstructionReferenceCase


def get_india_construction_reference_cases() -> List[ConstructionReferenceCase]:
    return [
        ConstructionReferenceCase(
            case_id="AP-TRUSS-01",
            sector="airport-terminal",
            design_name="Check-in Hall Steel Truss",
            target_status="conditional-approval",
            summary="Long-span roof truss with pending connection and vibration checks.",
            key_inputs={
                "span_m": 36,
                "bay_spacing_m": 8,
                "material": "E350 structural steel",
                "seismic_zone": "IV",
            },
            expected_issues=[
                "Connection detailing verification pending",
                "Vibration comfort check for crowd zone pending",
            ],
            standards=["IS 800", "IS 875", "IS 1893", "NBC 2016"],
        ),
        ConstructionReferenceCase(
            case_id="CU-SLAB-03",
            sector="customs-cargo",
            design_name="Forklift Bay RC Slab",
            target_status="rework-required",
            summary="Warehouse slab with axle and rack point-load overstress risk.",
            key_inputs={
                "slab_thickness_mm": 180,
                "forklift_axle_load_kN": 95,
                "rack_point_load_kN": 65,
                "material": "M30 + Fe500",
            },
            expected_issues=[
                "Punching/shear overstress at rack base",
                "Joint spacing too high for load class",
                "Wear topping spec missing",
            ],
            standards=["IS 456", "IS 875", "NBC 2016", "Warehouse SOP"],
        ),
        ConstructionReferenceCase(
            case_id="HR-CORE-04",
            sector="high-rise",
            design_name="RC Core + Egress Stair",
            target_status="approved",
            summary="Compliant stair core geometry and seismic detailing baseline.",
            key_inputs={
                "stair_width_mm": 1800,
                "riser_mm": 150,
                "tread_mm": 300,
                "core_wall_mm": 300,
            },
            expected_issues=[],
            standards=["NBC 2016", "IS 456", "IS 1893", "IS 13920"],
        ),
        ConstructionReferenceCase(
            case_id="AP-FIRE-06",
            sector="airport-terminal",
            design_name="Fire Stair Pressurization Shaft",
            target_status="rework-required",
            summary="Pressurization design with redundancy and smoke-control gaps.",
            key_inputs={
                "shaft_area_m2": 5.4,
                "doors_count": 14,
                "fan_redundancy": "N",
                "target_pressure_pa": 40,
            },
            expected_issues=[
                "Redundancy requirement not met",
                "Pressure target low for door opening scenario",
                "Smoke extraction integration missing",
            ],
            standards=["NBC 2016 Fire", "Local Fire NOC norms", "Airport EHS SOP"],
        ),
        ConstructionReferenceCase(
            case_id="CU-CANOPY-07",
            sector="customs-cargo",
            design_name="Truck Inspection Canopy",
            target_status="conditional-approval",
            summary="Inspection lane canopy mostly compliant with minor documentation gap.",
            key_inputs={
                "clear_height_m": 6.5,
                "lane_width_m": 4.2,
                "cantilever_m": 3.0,
                "wind_basic_speed_mps": 47,
            },
            expected_issues=["Drainage slope annotation incomplete"],
            standards=["IS 800", "IS 875", "NBC 2016", "Customs lane SOP"],
        ),
        ConstructionReferenceCase(
            case_id="RS-TWR-08",
            sector="residential-high-rise",
            design_name="G+25 Residential Tower Core",
            target_status="conditional-approval",
            summary="Core and egress layout generally compliant with pending refuge floor signage package.",
            key_inputs={
                "tower_height_m": 88,
                "stair_width_mm": 1600,
                "seismic_zone": "III",
                "concrete_grade": "M40",
            },
            expected_issues=["Refuge floor wayfinding and emergency signage package pending"],
            standards=["NBC 2016", "IS 456", "IS 1893", "IS 13920"],
        ),
        ConstructionReferenceCase(
            case_id="CM-MALL-09",
            sector="commercial-mall",
            design_name="Retail Atrium Transfer Beam",
            target_status="rework-required",
            summary="Transfer beam shows excessive service deflection under combined load.",
            key_inputs={
                "beam_span_m": 14.5,
                "beam_depth_mm": 1200,
                "live_load_kN_per_m2": 5,
                "finish_load_kN_per_m2": 1.5,
            },
            expected_issues=[
                "Serviceability deflection over target",
                "Crack width exceeds permissible envelope in long-term case",
            ],
            standards=["IS 456", "IS 875", "NBC 2016"],
        ),
        ConstructionReferenceCase(
            case_id="HP-ICU-10",
            sector="hospital",
            design_name="ICU Block HVAC Zoning",
            target_status="rework-required",
            summary="Clinical zoning is incomplete for pressure cascade and clean-dirty movement.",
            key_inputs={
                "icu_beds": 24,
                "air_changes_per_hour": 12,
                "backup_power_minutes": 15,
                "isolation_rooms": 2,
            },
            expected_issues=[
                "Pressure cascade not demonstrated across critical rooms",
                "Backup power autonomy below project target",
            ],
            standards=["NBC 2016", "NABH guidance", "Hospital MEP SOP"],
        ),
        ConstructionReferenceCase(
            case_id="ED-SCH-11",
            sector="school",
            design_name="K-12 Classroom Block",
            target_status="conditional-approval",
            summary="Academic block is compliant with minor accessibility annotation gap.",
            key_inputs={
                "floors": 4,
                "occupancy": 1800,
                "corridor_width_mm": 2400,
                "ramp_slope_percent": 8,
            },
            expected_issues=["Accessible toilet signage and tactile map details pending"],
            standards=["NBC 2016", "RPwD accessibility norms", "Local fire by-laws"],
        ),
        ConstructionReferenceCase(
            case_id="BR-FLY-12",
            sector="bridge-flyover",
            design_name="Urban Flyover Pier Cap",
            target_status="rework-required",
            summary="Bearing seat and reinforcement anchorage are not adequate for seismic demand.",
            key_inputs={
                "span_m": 32,
                "bearing_type": "elastomeric",
                "seismic_zone": "IV",
                "pier_height_m": 11,
            },
            expected_issues=[
                "Anchorage development length short in critical zone",
                "Bearing seat width below detailing recommendation",
            ],
            standards=["IRC bridge codes", "IS 1893", "IS 456"],
        ),
        ConstructionReferenceCase(
            case_id="MT-STN-13",
            sector="metro-station",
            design_name="Concourse Evacuation Layout",
            target_status="rework-required",
            summary="Peak-hour evacuation model indicates bottleneck at fare-gate throat.",
            key_inputs={
                "peak_pax_per_hour": 14000,
                "escalators": 6,
                "staircases": 4,
                "platform_length_m": 140,
            },
            expected_issues=[
                "Egress capacity short in emergency scenario",
                "Smoke extraction sequence not mapped to crowd model",
            ],
            standards=["NBC 2016", "Metro authority design manual", "Fire NOC requirements"],
        ),
        ConstructionReferenceCase(
            case_id="WT-PLNT-14",
            sector="water-treatment",
            design_name="Clear Water Reservoir Roof Slab",
            target_status="approved",
            summary="Reservoir slab and crack control checks pass for serviceability criteria.",
            key_inputs={
                "tank_capacity_mld": 45,
                "slab_thickness_mm": 300,
                "concrete_grade": "M35",
                "exposure_class": "severe",
            },
            expected_issues=[],
            standards=["IS 456", "CPHEEO manual", "NBC 2016"],
        ),
        ConstructionReferenceCase(
            case_id="UG-PKG-15",
            sector="basement-parking",
            design_name="B2 Ramp and Ventilation Bay",
            target_status="conditional-approval",
            summary="Vehicle flow and structure acceptable with pending CO sensor zoning update.",
            key_inputs={
                "ramp_gradient_percent": 12,
                "clear_height_m": 2.4,
                "parking_slots": 460,
                "ventilation_ach": 8,
            },
            expected_issues=["CO sensor and jet fan zoning drawing update pending"],
            standards=["NBC 2016", "Local fire code", "MEP parking ventilation SOP"],
        ),
        ConstructionReferenceCase(
            case_id="WH-LOG-16",
            sector="logistics-warehouse",
            design_name="Pre-Engineered Warehouse Frame",
            target_status="rework-required",
            summary="Frame bracing and purlin spacing are not adequate for local wind zone case.",
            key_inputs={
                "clear_span_m": 48,
                "eave_height_m": 12,
                "wind_basic_speed_mps": 50,
                "roof_slope_percent": 10,
            },
            expected_issues=[
                "Longitudinal bracing utilization above acceptable limit",
                "Roof uplift combinations exceed purlin capacity",
            ],
            standards=["IS 800", "IS 875", "NBC 2016"],
        ),
        ConstructionReferenceCase(
            case_id="IT-OFC-17",
            sector="office-tower",
            design_name="IT Park Podium Deck",
            target_status="conditional-approval",
            summary="Podium deck passes ultimate checks with pending waterproofing detail closure.",
            key_inputs={
                "podium_area_m2": 18500,
                "slab_system": "PT slab",
                "live_load_kN_per_m2": 4,
                "rainfall_intensity_mm_per_hr": 95,
            },
            expected_issues=["Waterproofing movement-joint detail not finalized"],
            standards=["IS 1343", "IS 456", "NBC 2016", "Project envelope spec"],
        ),
        ConstructionReferenceCase(
            case_id="SP-ARE-18",
            sector="sports-arena",
            design_name="Long-Span Roof Ring",
            target_status="rework-required",
            summary="Dynamic crowd and wind interaction requires higher damping strategy.",
            key_inputs={
                "roof_span_m": 92,
                "occupancy": 22000,
                "steel_grade": "E350",
                "wind_basic_speed_mps": 47,
            },
            expected_issues=[
                "Dynamic amplification exceeds comfort target",
                "Secondary bracing detailing incomplete for fatigue load path",
            ],
            standards=["IS 800", "IS 875", "NBC 2016", "Venue structural criteria"],
        ),
    ]
